import type { Metadata } from "next";
import Link from "next/link";
import { ClipboardCheck, FileCheck2, FlaskConical, Layers3, SearchCheck, Target } from "lucide-react";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { Card } from "@/components/ui/card";
import { Container } from "@/components/ui/container";
import { Icon } from "@/components/ui/icon";
import { Section } from "@/components/ui/section";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "Pharmaceuticals", description: "QCSV technology, validation and quality support for pharmaceutical environments." };
const services = [["Computer System Validation", "/services/computer-system-validation", ClipboardCheck], ["Quality Assurance", "/services/quality-assurance", Target], ["IT Infrastructure Qualification", "/services/it-infrastructure-qualification", Layers3], ["SAP Services", "/services/sap-services", Layers3], ["Project Documentation", "/services/project-documentation", FileCheck2], ["Project Management", "/services/project-management", Target]] as const;
const stories = [["SAP Validation", "UK", "Pharmaceuticals"], ["LIMS Validation", "US", "Pharmaceuticals"], ["SAP GAP Assessment", "Israel", "Pharmaceuticals"], ["SOP Preparation", "Israel", "Pharmaceuticals"], ["Empower 3 Validation", "US", "Pharmaceuticals"]] as const;

export default function PharmaceuticalsPage() { return <div className="min-h-screen bg-[var(--background)]"><Header /><main>
<section className="relative isolate overflow-hidden"><div aria-hidden="true" className="qcsv-ambient-glow -left-24 top-20" /><div aria-hidden="true" className="qcsv-ambient-glow -right-32 bottom-0 bg-[rgba(99,102,241,0.1)]" /><Container><div className="relative grid gap-12 py-20 md:py-28 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div className="max-w-3xl"><SectionHeading eyebrow="PHARMACEUTICALS" title="Technology, validation and quality support for pharmaceutical environments." description="Pharmaceutical organizations may rely on computerized systems, data, documentation and controlled project execution. QCSV supports these contexts through confirmed service areas." /><Link href="/#contact" className="mt-9 inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[var(--primary-hover)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--primary)]">Discuss your requirements</Link></div><Card className="relative overflow-hidden p-7 sm:p-9"><div aria-hidden="true" className="absolute -right-10 -top-10 h-32 w-32 rounded-full border border-[var(--primary)]/20 bg-[var(--primary)]/10" /><Icon icon={FlaskConical} size="lg" /><h2 className="mt-6 max-w-sm font-display text-2xl font-bold text-[var(--foreground)]">Technology and quality in a controlled context.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[var(--foreground-muted)]">Validation, lifecycle documentation, data integrity considerations and system changes can be important planning topics.</p></Card></div></Container></section>
<Section className="bg-[var(--surface)]"><Container><SectionHeading eyebrow="INDUSTRY CONTEXT" title="Support shaped around pharmaceutical technology and quality needs." description="Computerized system validation, lifecycle documentation, data integrity considerations, system changes and quality-focused delivery are general industry challenges. They do not describe an unconfirmed QCSV outcome or regulatory status." /></Container></Section>
<Section><Container><SectionHeading eyebrow="RELEVANT QCSV SERVICES" title="Service areas for pharmaceutical initiatives." description="These links reflect the service relationships approved in the content matrix. Specific project roles require confirmation." /><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(([name, href, icon]) => <Link key={name} href={href} className="block h-full rounded-[var(--radius-md)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--primary)]"><Card interactive className="flex h-full flex-col p-6"><Icon icon={icon} size="md" /><h2 className="mt-5 font-display text-lg font-semibold text-[var(--foreground)]">{name}</h2><span className="mt-6 text-sm font-semibold text-[var(--primary)]">Explore service <span aria-hidden="true">→</span></span></Card></Link>)}</div></Container></Section>
<Section className="bg-[var(--surface)]"><Container><SectionHeading eyebrow="TYPICAL CONSIDERATIONS" title="Technology, documentation and execution in view." description="Pharmaceutical technology initiatives may involve requirements, testing, validation documentation, data considerations, controlled changes and structured project delivery. QCSV-specific systems and methods require client confirmation." /><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Validation context", "Computerized systems and validation activities may need clear requirements and evidence."], ["Quality documentation", "Project records and lifecycle documentation can help keep decisions and activities organized."], ["Project execution", "Coordinated planning and delivery can connect technology, quality and project priorities."]].map(([title, text]) => <Card key={title} className="p-6"><h2 className="font-display text-lg font-semibold text-[var(--foreground)]">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--foreground-muted)]">{text}</p></Card>)}</div></Container></Section>
<Section><Container><SectionHeading eyebrow="CONFIRMED SUCCESS STORIES" title="Selected pharmaceutical engagements." description="Only confirmed title, geography and industry are shown. No challenge, approach or outcome is inferred." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{stories.map(([title, location, industry]) => <Card key={title} className="p-5"><Icon icon={SearchCheck} size="sm" /><h2 className="mt-4 font-display text-base font-semibold text-[var(--foreground)]">{title}</h2><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-[var(--foreground-subtle)]">{location} <span aria-hidden="true">•</span> {industry}</p></Card>)}</div></Container></Section>
<Section spacing="large"><Container><div className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-elevated)] px-6 py-12 text-center sm:px-10"><SectionHeading align="center" eyebrow="START A CONVERSATION" title="Discuss your pharmaceutical technology and quality requirements." description="Connect with QCSV to discuss the confirmed project context and appropriate support." /><Link href="/#contact" className="mt-8 inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[var(--primary-hover)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--primary)]">Talk to QCSV</Link></div></Container></Section>
</main><Footer /></div>; }
