import type { Metadata } from "next";
import Link from "next/link";
import { ClipboardCheck, Factory, FileCheck2, Network, SearchCheck, Workflow } from "lucide-react";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { Card } from "@/components/ui/card";
import { Container } from "@/components/ui/container";
import { Icon } from "@/components/ui/icon";
import { Section } from "@/components/ui/section";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "Regulated Manufacturing", description: "QCSV technology, quality and delivery support for regulated manufacturing environments." };
const services = [["Manufacturing Execution Systems", "/services/manufacturing-execution-systems", Factory], ["Serialization", "/services/serialization", Network], ["IT Infrastructure Qualification", "/services/it-infrastructure-qualification", SearchCheck], ["Computer System Validation", "/services/computer-system-validation", ClipboardCheck], ["Quality Assurance", "/services/quality-assurance", FileCheck2], ["Project Management", "/services/project-management", Workflow]] as const;
export default function RegulatedManufacturingPage() { return <div className="min-h-screen bg-[var(--background)]"><Header /><main>
<section className="relative isolate overflow-hidden"><div aria-hidden="true" className="qcsv-ambient-glow -left-24 top-20" /><div aria-hidden="true" className="qcsv-ambient-glow -right-32 bottom-0 bg-[rgba(99,102,241,0.1)]" /><Container><div className="relative grid gap-12 py-20 md:py-28 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div className="max-w-3xl"><SectionHeading eyebrow="REGULATED MANUFACTURING" title="Technology, quality and delivery support for regulated manufacturing environments." description="Regulated manufacturing environments may connect production, technology, quality, documentation and controlled project activities." /><Link href="/#contact" className="mt-9 inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[var(--primary-hover)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--primary)]">Discuss your requirements</Link></div><Card className="relative overflow-hidden p-7 sm:p-9"><div aria-hidden="true" className="absolute -right-10 -top-10 h-32 w-32 rounded-full border border-[var(--primary)]/20 bg-[var(--primary)]/10" /><Icon icon={Factory} size="lg" /><h2 className="mt-6 max-w-sm font-display text-2xl font-bold text-[var(--foreground)]">Production, technology and quality in view.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[var(--foreground-muted)]">Manufacturing technology coordination, infrastructure, documentation, traceability and project execution can shape the work.</p></Card></div></Container></section>
<Section className="bg-[var(--surface)]"><Container><SectionHeading eyebrow="INDUSTRY CONTEXT" title="A manufacturing context for connected technology and quality work." description="Regulated manufacturing may involve production technology, system qualification, documentation, data and traceability considerations, project execution and quality review. This is general context, not a compliance claim." /></Container></Section>
<Section><Container><SectionHeading eyebrow="RELEVANT QCSV SERVICES" title="Service areas for regulated manufacturing initiatives." description="These service relationships are approved in the content matrix. Manufacturing subsector, systems and QCSV experience require confirmation." /><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(([name, href, icon]) => <Link key={name} href={href} className="block h-full rounded-[var(--radius-md)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--primary)]"><Card interactive className="flex h-full flex-col p-6"><Icon icon={icon} size="md" /><h2 className="mt-5 font-display text-lg font-semibold text-[var(--foreground)]">{name}</h2><span className="mt-6 text-sm font-semibold text-[var(--primary)]">Explore service <span aria-hidden="true">→</span></span></Card></Link>)}</div></Container></Section>
<Section className="bg-[var(--surface)]"><Container><SectionHeading eyebrow="TYPICAL CONSIDERATIONS" title="Technology, data, documentation and execution connected." description="Regulated manufacturing projects may involve manufacturing technology coordination, infrastructure and system qualification, documentation, data and traceability considerations, project execution and quality review." /><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Manufacturing technology", "Coordinate systems and information connected to production activities."], ["Documentation and data", "Keep records, data and traceability considerations visible."], ["Quality and execution", "Connect quality review with structured project delivery."]].map(([title, text]) => <Card key={title} className="p-6"><h2 className="font-display text-lg font-semibold text-[var(--foreground)]">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--foreground-muted)]">{text}</p></Card>)}</div></Container></Section>
<Section><Container><Card className="max-w-xl p-7 sm:p-9"><Icon icon={SearchCheck} size="md" /><h2 className="mt-5 font-display text-2xl font-bold text-[var(--foreground)]">No directly confirmed Regulated Manufacturing story is presented.</h2><p className="mt-3 text-sm leading-6 text-[var(--foreground-muted)]">Equipment Qualification and SAP Technical Upgrade may inform adjacent context, but the current material does not relabel either story as Regulated Manufacturing.</p></Card></Container></Section>
<Section spacing="large"><Container><div className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-elevated)] px-6 py-12 text-center sm:px-10"><SectionHeading align="center" eyebrow="START A CONVERSATION" title="Discuss your regulated manufacturing technology requirements." description="Connect with QCSV to discuss the confirmed project context and appropriate support." /><Link href="/#contact" className="mt-8 inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[var(--primary-hover)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--primary)]">Talk to QCSV</Link></div></Container></Section>
</main><Footer /></div>; }
