import type { Metadata } from "next";
import Link from "next/link";
import { Cloud, FileCheck2, FlaskConical, SearchCheck, Target, Workflow } from "lucide-react";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { Card } from "@/components/ui/card";
import { Container } from "@/components/ui/container";
import { Icon } from "@/components/ui/icon";
import { Section } from "@/components/ui/section";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "Life Sciences", description: "QCSV technology, validation and quality context for life-sciences organizations." };
const services = [["Computer System Validation", "/services/computer-system-validation", FlaskConical], ["Quality Assurance", "/services/quality-assurance", Target], ["Project Documentation", "/services/project-documentation", FileCheck2], ["Project Management", "/services/project-management", Workflow], ["IT Infrastructure Qualification", "/services/it-infrastructure-qualification", SearchCheck], ["Cloud Services", "/services/cloud-services", Cloud]] as const;
export default function LifeSciencesPage() { return <div className="min-h-screen bg-[var(--background)]"><Header /><main>
<section className="relative isolate overflow-hidden"><div aria-hidden="true" className="qcsv-ambient-glow -left-24 top-20" /><div aria-hidden="true" className="qcsv-ambient-glow -right-32 bottom-0 bg-[rgba(99,102,241,0.1)]" /><Container><div className="relative grid gap-12 py-20 md:py-28 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div className="max-w-3xl"><SectionHeading eyebrow="LIFE SCIENCES" title="Technology, validation and quality support for life-sciences organizations." description="Life-sciences organizations may rely on technology, data, validation and quality activities across research, development, production or support operations." /><Link href="/#contact" className="mt-9 inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[var(--primary-hover)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--primary)]">Discuss your requirements</Link></div><Card className="relative overflow-hidden p-7 sm:p-9"><div aria-hidden="true" className="absolute -right-10 -top-10 h-32 w-32 rounded-full border border-[var(--primary)]/20 bg-[var(--primary)]/10" /><Icon icon={FlaskConical} size="lg" /><h2 className="mt-6 max-w-sm font-display text-2xl font-bold text-[var(--foreground)]">Technology and data across connected operations.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[var(--foreground-muted)]">Validation, documentation, quality activities and project change considerations can shape life-sciences technology work.</p></Card></div></Container></section>
<Section className="bg-[var(--surface)]"><Container><SectionHeading eyebrow="INDUSTRY CONTEXT" title="A broad context for technology, data and quality activities." description="Life-sciences organizations may coordinate technology initiatives, document requirements, support validation and quality activities, and manage data and project change considerations. This is general context only." /></Container></Section>
<Section><Container><SectionHeading eyebrow="RELEVANT QCSV SERVICES" title="Service areas for life-sciences technology initiatives." description="These relationships are approved as relevant service areas. Sub-industry focus, systems and QCSV experience require confirmation." /><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(([name, href, icon]) => <Link key={name} href={href} className="block h-full rounded-[var(--radius-md)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--primary)]"><Card interactive className="flex h-full flex-col p-6"><Icon icon={icon} size="md" /><h2 className="mt-5 font-display text-lg font-semibold text-[var(--foreground)]">{name}</h2><span className="mt-6 text-sm font-semibold text-[var(--primary)]">Explore service <span aria-hidden="true">→</span></span></Card></Link>)}</div></Container></Section>
<Section className="bg-[var(--surface)]"><Container><SectionHeading eyebrow="TYPICAL CONSIDERATIONS" title="Clear requirements, quality activities and managed change." description="Life-sciences technology initiatives may involve requirements documentation, validation support, quality coordination, data considerations and project change management. Specific systems and outcomes require client confirmation." /><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Requirements", "Document technology and project needs clearly."], ["Validation and quality", "Coordinate validation and quality activities within the confirmed scope."], ["Change context", "Keep data and project change considerations visible."]].map(([title, text]) => <Card key={title} className="p-6"><h2 className="font-display text-lg font-semibold text-[var(--foreground)]">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--foreground-muted)]">{text}</p></Card>)}</div></Container></Section>
<Section><Container><Card className="max-w-xl p-7 sm:p-9"><Icon icon={SearchCheck} size="md" /><h2 className="mt-5 font-display text-2xl font-bold text-[var(--foreground)]">No Life Sciences-specific success story is confirmed.</h2><p className="mt-3 text-sm leading-6 text-[var(--foreground-muted)]">The current QCSV material does not confirm a Life Sciences-specific engagement. No story is inferred from the Pharmaceuticals category.</p></Card></Container></Section>
<Section spacing="large"><Container><div className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-elevated)] px-6 py-12 text-center sm:px-10"><SectionHeading align="center" eyebrow="START A CONVERSATION" title="Discuss your life-sciences technology requirements." description="Connect with QCSV to discuss the confirmed project context and appropriate support." /><Link href="/#contact" className="mt-8 inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[var(--primary-hover)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--primary)]">Talk to QCSV</Link></div></Container></Section>
</main><Footer /></div>; }
