import type { Metadata } from "next";
import Link from "next/link";
import { FileCheck2, HardDrive, Layers3, Microchip, SearchCheck, Workflow } from "lucide-react";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { Card } from "@/components/ui/card";
import { Container } from "@/components/ui/container";
import { Icon } from "@/components/ui/icon";
import { Section } from "@/components/ui/section";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "Semiconductor", description: "QCSV technology and project support for semiconductor and technology-driven manufacturing." };
const services = [["SAP Services", "/services/sap-services", Layers3], ["Manufacturing Execution Systems", "/services/manufacturing-execution-systems", Workflow], ["IT Infrastructure Qualification", "/services/it-infrastructure-qualification", HardDrive], ["Project Management", "/services/project-management", SearchCheck], ["Project Documentation", "/services/project-documentation", FileCheck2], ["Quality Assurance", "/services/quality-assurance", Microchip]] as const;
export default function SemiconductorPage() { return <div className="min-h-screen bg-[var(--background)]"><Header /><main>
<section className="relative isolate overflow-hidden"><div aria-hidden="true" className="qcsv-ambient-glow -left-24 top-20" /><div aria-hidden="true" className="qcsv-ambient-glow -right-32 bottom-0 bg-[rgba(99,102,241,0.1)]" /><Container><div className="relative grid gap-12 py-20 md:py-28 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div className="max-w-3xl"><SectionHeading eyebrow="SEMICONDUCTOR" title="Technology and project support for semiconductor and technology-driven manufacturing." description="Semiconductor organizations operate technology-driven manufacturing environments where enterprise systems, production information, infrastructure and project execution may be important." /><Link href="/#contact" className="mt-9 inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[var(--primary-hover)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--primary)]">Discuss your requirements</Link></div><Card className="relative overflow-hidden p-7 sm:p-9"><div aria-hidden="true" className="absolute -right-10 -top-10 h-32 w-32 rounded-full border border-[var(--primary)]/20 bg-[var(--primary)]/10" /><Icon icon={Microchip} size="lg" /><h2 className="mt-6 max-w-sm font-display text-2xl font-bold text-[var(--foreground)]">A technology-driven manufacturing context.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[var(--foreground-muted)]">Enterprise technology upgrades, manufacturing-system coordination, documentation and controlled change can shape project delivery.</p></Card></div></Container></section>
<Section className="bg-[var(--surface)]"><Container><SectionHeading eyebrow="INDUSTRY CONTEXT" title="Technology-driven manufacturing with project execution in view." description="Semiconductor is represented as a technology-driven and regulated manufacturing industry based on the confirmed QCSV success story. Manufacturing systems, platforms and project roles require confirmation." /></Container></Section>
<Section><Container><SectionHeading eyebrow="RELEVANT QCSV SERVICES" title="Service areas for semiconductor technology initiatives." description="These service relationships are drawn from the approved content matrix. Specific manufacturing systems, platforms and QCSV roles require confirmation." /><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(([name, href, icon]) => <Link key={name} href={href} className="block h-full rounded-[var(--radius-md)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--primary)]"><Card interactive className="flex h-full flex-col p-6"><Icon icon={icon} size="md" /><h2 className="mt-5 font-display text-lg font-semibold text-[var(--foreground)]">{name}</h2><span className="mt-6 text-sm font-semibold text-[var(--primary)]">Explore service <span aria-hidden="true">→</span></span></Card></Link>)}</div></Container></Section>
<Section className="bg-[var(--surface)]"><Container><SectionHeading eyebrow="TYPICAL CONSIDERATIONS" title="Enterprise systems, production information and controlled delivery." description="Semiconductor technology projects may involve enterprise technology upgrades, manufacturing-system coordination, technology project delivery, documentation and controlled change considerations. These are general context only." /><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Enterprise technology", "Coordinate technology work connected to core operations."], ["Manufacturing information", "Consider production information and system coordination."], ["Project delivery", "Keep documentation, dependencies and changes visible."]].map(([title, text]) => <Card key={title} className="p-6"><h2 className="font-display text-lg font-semibold text-[var(--foreground)]">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--foreground-muted)]">{text}</p></Card>)}</div></Container></Section>
<Section><Container><SectionHeading eyebrow="CONFIRMED SUCCESS STORY" title="SAP Technical Upgrade." description="The confirmed QCSV relationship is shown without additional technology, challenge or outcome details." /><Card className="mt-10 max-w-md p-6"><Icon icon={Layers3} size="md" /><h2 className="mt-5 font-display text-lg font-semibold text-[var(--foreground)]">SAP Technical Upgrade</h2><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-[var(--foreground-subtle)]">US <span aria-hidden="true">•</span> Semiconductor</p></Card></Container></Section>
<Section spacing="large"><Container><div className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-elevated)] px-6 py-12 text-center sm:px-10"><SectionHeading align="center" eyebrow="START A CONVERSATION" title="Discuss your semiconductor technology or delivery requirements." description="Connect with QCSV to discuss the confirmed project context and appropriate support." /><Link href="/#contact" className="mt-8 inline-flex min-h-11 items-center justify-center rounded-[var(--radius-md)] bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[var(--primary-hover)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--primary)]">Talk to QCSV</Link></div></Container></Section>
</main><Footer /></div>; }
